# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Newman Tests by Postman.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra
      
          # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
          newman run collections/Openweathermap.postman_collection.json --iteration-data dataset/data.json -r htmlextra --reporter-htmlextra-export testResults/index.html
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: testResults
         
      - name: Step 4 - Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages-newman
          path: gh-pages-newman
          
      - name: Step 6 - Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages-newman
            PUBLISH_DIR: testResults
