# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Newman Tests by Postman.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
        # 1 - Step - Install dependences.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra

      # 2 -Step - Run the POSTMAN collection
      - name: Step 2 - Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
          mkdir -p testResults
          newman run collections/Openweathermap.postman_collection.json --iteration-data dataset/data.json -r htmlextra --reporter-htmlextra-export testResults/index.html
      
      # 3 - Steps - Upload the contents of Test Results directory to workspace
      - name: Step 3 - Output the run Details
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: testResults
         
      # 4 - Steps - Allure History
      - name: Step 4 - Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages-newman
          path: gh-pages-newman
          
      # Step 5 - Deploy report to Github Pages
      - name: Step 5 - Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages-newman
            PUBLISH_DIR: testResults
            
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: reiload
          # Optional (recommended) mail server password:
          password: ${{secrets.PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: reiload@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: file://README.md
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: index.html
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
