# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Newman Tests by Postman.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  newman:
    runs-on: windows-latest
    steps:
        # 1 - Step - Install dependences.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g newman | 
             npm install -g allure-commandline --save-dev |
             npm install -g newman-reporter-allure 

      # 2 -Step - Run the POSTMAN collection
      - name: Step 2 - Run POSTMAN collection
        if: always()
        continue-on-error: true
        run: |
             newman run collections/Openweathermap.postman_collection.json --iteration-data dataset/data.json -r allure
        
      - name: Mostra as pastas
        run: ls -la
      - name:  Step 4 - Collect Allure files and generate allure-report folder
        run: |
          allure generate ./allure-results -o allure-report/
      - name: 🎁 Step 4 - Publishing Allure artifact to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          
      # Step 5 - Deploy report to Github Pages
      - name: Step 5 - Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages-newman
            PUBLISH_DIR: allure-report
            
